# Generated by Django 4.2.7 on 2025-10-15 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
