#!/bin/bash
set -o errexit

python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py collectstatic --noinput

celery -A notification worker -l DEBUG --detach
celery -A notification beat -l INFO --detach

python3 manage.py runserver 0.0.0.0:9081 --settings=notification.settings.local