#!/bin/bash
set -o errexit

python3 manage.py makemigrations
python3 manage.py migrate
python3 manage.py collectstatic --noinput



python3 manage.py runserver "0.0.0.0:${DJANGO_LISTENING_PORT:-9081}"