upstream django {
   server api:{{ django_listening_port }};
}

server {
   client_max_body_size 20M;
   listen 80;

   location / {

      # An HTTP header important enough to have its own Wikipedia entry: http://en.wikipedia.org/wiki/X-Forwarded-For
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;

      # Set the header X-forwaded-proto so that Django can know the scheme of the request (this will be http)
      proxy_set_header X-Forwarded-Proto $scheme;


      # Pass the Host: header from the client right along so redirects can be set properly
      proxy_set_header Host $http_host;

      # we don't want nginx trying to do something clever with redirects, we set the Host: header above already.
      proxy_redirect off;

      # Try to serve static files from nginx, no point in making an
      # *application* server like Unicorn/Rainbows! serve static files.
      if (!-f $request_filename) {
        proxy_pass http://django;
        break;
      }
   }

   # The main purpose of nginx here is to server static files to let's him do it.
   location /static/ {
      alias /app/static/;
   }

   location /media/ {
      alias /app/media/;
   }
}
