# https://stackoverflow.com/questions/44694640/docker-swarm-with-image-versions-externalized-to-env-file
# See https://www.pgadmin.org/docs/pgadmin4/latest/container_deployment.html
services:
  nginx:
    image: nginx:1.21.5-alpine
    configs:
      - source: "{{ nginx_config_name }}"
        target: /etc/nginx/conf.d/default.conf
        mode: 0440
    volumes:
      - static_volume:/app/static:ro
      - media_volume:/app/media:ro

    networks:
      - klivar
      - "{{ traefik_network }}"

    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      rollback_config:
        order: start-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=true
        - traefik.constraint-label=traefik-public

        # Http router: redirection to https
        - traefik.http.routers.{{ env }}-nginx-tmp-back-http.rule=Host(`{{ tmp_back_hostname }}`)
        - traefik.http.routers.{{ env }}-nginx-tmp-back-http.entrypoints=http
        - traefik.http.routers.{{ env }}-nginx-tmp-back-http.middlewares=https-redirect

        # Https router
        - traefik.http.routers.{{ env }}-nginx-tmp-back-https.rule=Host(`{{ tmp_back_hostname }}`)
        - traefik.http.routers.{{ env }}-nginx-tmp-back-https.entrypoints=https
        - traefik.http.routers.{{ env }}-nginx-tmp-back-https.tls=true
        - traefik.http.routers.{{ env }}-nginx-tmp-back-https.tls.certresolver=letsencrypt

        # Pointing to nginx (for serving static files)
        - traefik.http.services.{{ env }}-nginx-tmp-back.loadbalancer.server.port=80


  api: &api
    image: "{{ tmp_back_image }}"
    command: /start
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    networks:
      - klivar
    env_file:
      - ./.django.env
      - ./.postgres.env


    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      rollback_config:
        order: start-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
      placement:
        constraints:
          - node.role == manager

  redis:
    image: redis:6-alpine
    networks:
      - klivar
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - traefik.enable=false

  celery_worker:
    <<: *api
    command: /start-celeryworker
    healthcheck: # TODO: needs to be implemented
      test: []
      disable: true

  celery_beat:
    <<: *api
    command: /start-beat
    healthcheck: # TODO: needs to be implemented
      test: []
      disable: true

  flower:
    <<: *api
    command: /start-flower
    healthcheck: # TODO: needs to be implemented
      test: []
      disable: true

 # Ajoutez simplement ce bloc dans votre fichier docker-stack.yml existant
# après le service "api" et avant "redis"

  # Service Daphne pour WebSockets
  daphne:
    <<: *api
    image: "{{ tmp_back_image }}"
    command: /start-daphne
    expose:
      - "9082"
    networks:
      - klivar
    env_file:
      - ./.django.env
      - ./.postgres.env
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        order: start-first
        parallelism: 1
        failure_action: rollback
      rollback_config:
        order: start-first
        parallelism: 1
      restart_policy:
        condition: on-failure
      labels:
        - traefik.enable=false
      placement:
        constraints:
          - node.role == manager

  kafka-consumer:
    <<: *api
    command: /start-kafka
    healthcheck: # TODO: needs to be implemented
      test: []
      disable: true

volumes:
  static_volume:
  media_volume:
  # es_data:

networks:
  klivar:
    name: "{{ env }}-tmp-back"
  "{{ traefik_network }}":
    external: true

configs:
  "{{ nginx_config_name }}":
    external: true
