# Generated by Django 4.2.7 on 2025-05-29 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientauthmail',
            name='client_id',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientauthmail',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
