# Generated by Django 4.2.7 on 2025-05-29 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0002_alter_clientauthmail_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientauthmail',
            name='url_auth_code',
        ),
        migrations.AddField(
            model_name='clientauthmail',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
