# Generated by Django 4.2.7 on 2025-05-29 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0003_remove_clientauthmail_url_auth_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientauthmail',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
