# Generated by Django 4.2.7 on 2025-05-29 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0005_authcodeclient'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientauthmail',
            name='surfix',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
