# Generated by Django 4.2.7 on 2025-05-31 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0006_clientauthmail_surfix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientauthmail',
            old_name='jwt_token',
            new_name='token',
        ),
    ]
