# Generated by Django 4.2.7 on 2025-05-31 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0007_rename_jwt_token_clientauthmail_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientauthmail',
            name='url_verification',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
