# Generated by Django 4.2.7 on 2025-08-06 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authClient', '0010_deviseauthmail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DeviseAuthMail',
        ),
    ]
