version: "3.8"

services:

  redis:
    image: redis:6-alpine
    networks:
      - klivar-api-local-live-nw
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5

  api: &api
    build:
      context: .
      dockerfile: ./docker/local/django/Dockerfile
    command: /start
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    expose:
      - "9081"
    networks:
      - klivar-api-local-live-nw
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    depends_on:
      - redis

  # Nouveau service Daphne pour WebSockets
  daphne:
    <<: *api
    image: klivar-backend-daphne
    command: /start-daphne
    expose:
      - "9082"
    networks:
      - klivar-api-local-live-nw
    env_file:
      - ./.envs/.local/.postgres
      - ./.envs/.local/.django
    depends_on:
      - redis
    volumes:
      - .:/app

  celery_worker:
    <<: *api
    image: klivar-backend-celeryworker
    command: /start-celeryworker
    healthcheck:
      test: []
      disable: true
    networks:
      - klivar-api-local-live-nw
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    volumes:
      - .:/app
    depends_on:
      redis:
        condition: service_healthy

  celery_beat:
    <<: *api
    image: klivar-backend-celerybeat
    command: /start-beat
    healthcheck:
      test: []
      disable: true
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    networks:
      - klivar-api-local-live-nw
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    <<: *api
    image: klivar-backend-flower
    command: /start-flower
    healthcheck:
      test: []
      disable: true
    env_file:
      - ./.envs/.local/.django
      - ./.envs/.local/.postgres
    networks:
      - klivar-api-local-live-nw
    volumes:
      - .:/app
    depends_on:
      - redis

  nginx:
    restart: always
    depends_on:
      - api
      - daphne
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/mediafiles
    build:
      context: ./docker/local/nginx
      dockerfile: Dockerfile
    ports:
      - "8083:80"
    networks:
      - klivar-api-local-live-nw

networks:
  klivar-api-local-live-nw:
    external: true

volumes:
  static_volume:
  media_volume: