# Generated by Django 4.2.7 on 2025-08-06 03:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='authCodeClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='DeviseAuthMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('device_type', models.CharField(blank=True, max_length=255, null=True)),
                ('device_name', models.CharField(blank=True, max_length=255, null=True)),
                ('browser_version', models.CharField(blank=True, max_length=255, null=True)),
                ('device_fingerprint', models.CharField(blank=True, max_length=255, null=True)),
                ('request_path', models.CharField(blank=True, max_length=255, null=True)),
                ('forwarded_ips', models.CharField(blank=True, max_length=255, null=True)),
                ('url_connect', models.CharField(blank=True, max_length=255, null=True)),
                ('url_verification', models.CharField(blank=True, max_length=255, null=True)),
                ('base_url', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.TextField(blank=True, null=True)),
                ('client_id', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_send', models.BooleanField(default=False)),
                ('lang', models.CharField(blank=True, max_length=10, null=True)),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('surfix', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmailVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
