# Generated by Django 4.2.7 on 2025-08-06 03:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_security', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authCodeClient',
            new_name='authCode',
        ),
    ]
