# Generated by Django 4.2.7 on 2025-08-06 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_security', '0003_deviseauthmail_os_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviseauthmail',
            name='browser_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
