# Generated by Django 4.2.7 on 2025-08-06 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_security', '0004_deviseauthmail_browser_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviseauthmail',
            name='browser_version',
        ),
        migrations.RemoveField(
            model_name='deviseauthmail',
            name='forwarded_ips',
        ),
    ]
