# Generated by Django 4.2.7 on 2025-08-06 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alert_security', '0005_remove_deviseauthmail_browser_version_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deviseauthmail',
            name='request_path',
        ),
    ]
