# Generated by Django 4.2.7 on 2025-08-06 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alert_security', '0006_remove_deviseauthmail_request_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviseauthmail',
            name='device_id',
            field=models.IntegerField(default=0),
        ),
    ]
