# Generated by Django 4.2.7 on 2025-10-24 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlertIndicatorEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instance', models.IntegerField(blank=True, null=True)),
                ('id_project', models.IntegerField(blank=True, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('seuil', models.CharField(blank=True, max_length=255, null=True)),
                ('date_alert', models.CharField(blank=True, max_length=255, null=True)),
                ('reporting_title', models.CharField(blank=True, max_length=255, null=True)),
                ('percent_value', models.CharField(blank=True, max_length=255, null=True)),
                ('url_connect', models.CharField(blank=True, max_length=255, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
