# Generated by Django 4.2.7 on 2025-10-24 12:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0002_alertindicatoremail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alertindicatoremail',
            old_name='id_instance',
            new_name='id_indicator',
        ),
        migrations.AddField(
            model_name='alertindicatoremail',
            name='actors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AddField(
            model_name='alertindicatoremail',
            name='client',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
