# Generated by Django 4.2.7 on 2025-10-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet', '0003_rename_id_instance_alertindicatoremail_id_indicator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='alertindicatoremail',
            name='msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alertindicatoremail',
            name='description',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
