# Generated by Django 4.2.7 on 2025-11-24 14:17

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissionAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mission_name', models.CharField(max_length=255, null=True)),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('mission_type', models.CharField(max_length=20, null=True)),
                ('status', models.CharField(max_length=20, null=True)),
                ('priority', models.CharField(max_length=20, null=True)),
                ('duree', models.CharField(max_length=100, null=True)),
                ('start_date', models.DateTimeField(help_text='Date de lancement de la mission', verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('deadline', models.DateTimeField(blank=True, help_text='Date limite absolue pour la completion', null=True, verbose_name='Date limite')),
                ('auditor_name', models.CharField(max_length=255, null=True)),
                ('auditor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'auditeur")),
                ('client_name', models.CharField(blank=True, max_length=255, null=True)),
                ('client_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du client')),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, help_text='Liste des domaines/processus à auditer', null=True, size=None, verbose_name="Périmètres d'audit")),
                ('departments', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, help_text='Services/départements impliqués', null=True, size=None, verbose_name='Départements concernés')),
                ('access_url', models.URLField(blank=True, help_text="Lien vers l'interface d'audit", null=True, verbose_name="URL d'accès au module")),
                ('documentation_url', models.URLField(blank=True, help_text='Lien vers les documents de référence', null=True, verbose_name='URL de la documentation')),
                ('base_url', models.URLField(blank=True, help_text='URL de base pour les ressources (images, etc.)', null=True, verbose_name='URL de base')),
                ('jwt_token', models.TextField(blank=True, help_text="Token d'authentification pour l'accès", null=True, verbose_name='Token JWT')),
                ('access_code', models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=50, null=True, verbose_name="Code d'accès")),
                ('id_client', models.BigIntegerField(blank=True, null=True, verbose_name='ID Client')),
                ('id_project', models.BigIntegerField(blank=True, null=True, verbose_name='ID Projet')),
                ('external_reference', models.CharField(blank=True, help_text='Référence dans un système externe', max_length=100, null=True, verbose_name='Référence externe')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Langue de communication')),
                ('send_notifications', models.BooleanField(default=True, help_text="Activer/désactiver l'envoi automatique d'emails", verbose_name='Envoyer les notifications')),
                ('launch_email_sent', models.BooleanField(default=False, verbose_name='Email de lancement envoyé')),
                ('launch_email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name="Date d'envoi email de lancement")),
                ('reminder_email_sent', models.BooleanField(default=False, verbose_name='Email de rappel envoyé')),
                ('completion_email_sent', models.BooleanField(default=False, verbose_name='Email de completion envoyé')),
                ('email_task_id', models.CharField(blank=True, help_text='ID de la tâche Celery pour le suivi', max_length=255, null=True, verbose_name='ID de la tâche email')),
                ('notes', models.TextField(blank=True, help_text='Commentaires ou remarques internes', null=True, verbose_name='Notes internes')),
                ('created_by', models.CharField(blank=True, help_text='Utilisateur qui a créé la mission', max_length=255, null=True, verbose_name='Créé par')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
            ],
            options={
                'verbose_name': 'Exigence',
                'verbose_name_plural': 'Exigences',
                'ordering': ['-created_at'],
            },
        ),
    ]
