# Generated by Django 4.2.7 on 2025-11-24 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='missionaudit',
            name='client_email',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='completion_email_sent',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='deadline',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='departments',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='documentation_url',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='duree',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='email_task_id',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='external_reference',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='launch_email_sent',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='launch_email_sent_at',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='mission_name',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='priority',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='reminder_email_sent',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='scope',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='send_notifications',
        ),
        migrations.RemoveField(
            model_name='missionaudit',
            name='status',
        ),
    ]
