# Generated by Django 4.2.7 on 2025-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0002_remove_missionaudit_client_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaudit',
            name='is_demande',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='missionaudit',
            name='is_mission',
            field=models.BooleanField(default=False),
        ),
    ]
