# Generated by Django 4.2.7 on 2025-11-24 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0003_missionaudit_is_demande_missionaudit_is_mission'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaudit',
            name='test',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
