# Generated by Django 4.2.7 on 2025-11-25 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0004_missionaudit_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='missionaudit',
            name='expires_code_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='missionaudit',
            name='id_demande',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Projet'),
        ),
        migrations.AlterField(
            model_name='missionaudit',
            name='jwt_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
