# Generated by Django 4.2.7 on 2025-11-25 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0005_missionaudit_expires_code_at_missionaudit_id_demande_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, null=True)),
                ('description', models.TextField(null=True)),
                ('mission_type', models.CharField(max_length=20, null=True)),
                ('start_date', models.DateTimeField(help_text='Date de lancement de la mission', verbose_name='Date de début')),
                ('end_date', models.DateTimeField(blank=True, null=True, verbose_name='Date de fin prévue')),
                ('auditor_name', models.CharField(max_length=255, null=True)),
                ('auditor_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name="Email de l'auditeur")),
                ('company', models.CharField(blank=True, max_length=255, null=True)),
                ('access_url', models.URLField(blank=True, help_text="Lien vers l'interface d'audit", null=True, verbose_name="URL d'accès au module")),
                ('base_url', models.URLField(blank=True, help_text='URL de base pour les ressources (images, etc.)', null=True, verbose_name='URL de base')),
                ('access_code', models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=50, null=True, verbose_name="Code d'accès")),
                ('id_client', models.BigIntegerField(blank=True, null=True, verbose_name='ID Client')),
                ('id_project', models.BigIntegerField(blank=True, null=True, verbose_name='ID Projet')),
                ('id_demande', models.BigIntegerField(blank=True, null=True, verbose_name='ID Projet')),
                ('language', models.CharField(blank=True, max_length=10, null=True, verbose_name='Langue de communication')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date de modification')),
                ('is_mission', models.BooleanField(default=False)),
                ('is_demande', models.BooleanField(default=False)),
                ('test', models.CharField(blank=True, max_length=255, null=True)),
                ('jwt_token', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_code_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Exigence',
                'verbose_name_plural': 'Exigences',
                'ordering': ['-created_at'],
            },
        ),
    ]
