# Generated by Django 4.2.7 on 2025-11-25 10:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0006_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MissionAudit',
        ),
    ]
