# Generated by Django 4.2.7 on 2025-11-25 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0007_delete_missionaudit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='jwt_token',
            field=models.TextField(blank=True, help_text="Token d'authentification pour l'accès", null=True, verbose_name='Token JWT'),
        ),
    ]
