# Generated by Django 4.2.7 on 2025-11-25 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0008_alter_task_jwt_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='access_url',
        ),
    ]
