# Generated by Django 4.2.7 on 2025-11-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0009_remove_task_access_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='access_url',
            field=models.TextField(blank=True, help_text="Token d'authentification pour l'accès", null=True, verbose_name='Token JWT'),
        ),
    ]
