# Generated by Django 4.2.7 on 2025-11-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0010_task_access_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('id_test', models.BigIntegerField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='id_test',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='ID Projet'),
        ),
        migrations.AddField(
            model_name='task',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='task',
            name='lieu',
            field=models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=255, null=True, verbose_name="Code d'accès"),
        ),
        migrations.AddField(
            model_name='task',
            name='scope_test',
            field=models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=255, null=True, verbose_name="Code d'accès"),
        ),
        migrations.AddField(
            model_name='task',
            name='type_test',
            field=models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=50, null=True, verbose_name="Code d'accès"),
        ),
        migrations.AddField(
            model_name='task',
            name='type_test_label',
            field=models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=50, null=True, verbose_name="Code d'accès"),
        ),
        migrations.CreateModel(
            name='ActorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, null=True)),
                ('id_user', models.BigIntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('task_id', models.CharField(blank=True, max_length=255, null=True)),
                ('jwt_token', models.TextField(blank=True, null=True)),
                ('follow_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_follow_up', to='auditor.followup')),
            ],
        ),
    ]
