# Generated by Django 4.2.7 on 2025-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0011_followup_task_id_test_task_is_test_task_lieu_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='start_date',
            field=models.DateTimeField(blank=True, help_text='Date de lancement de la mission', null=True, verbose_name='Date de début'),
        ),
    ]
