# Generated by Django 4.2.7 on 2025-11-26 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditor', '0012_alter_task_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='audit_method',
            field=models.CharField(blank=True, help_text="Code d'accès temporaire si nécessaire", max_length=255, null=True, verbose_name="Code d'accès"),
        ),
    ]
