# Generated by Django 4.2.7 on 2025-12-04 22:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reading_reminders', models.BooleanField(default=True, verbose_name='Rappels de lecture')),
                ('verse_of_day', models.BooleanField(default=True, verbose_name='Verset du jour')),
                ('couple_notifications', models.BooleanField(default=True, verbose_name='Notifications de couple')),
                ('reading_plan_updates', models.BooleanField(default=True, verbose_name='Mises à jour des plans')),
                ('achievements', models.BooleanField(default=True, verbose_name='Réussites')),
                ('general_notifications', models.BooleanField(default=True, verbose_name='Notifications générales')),
                ('reminder_time', models.TimeField(default=datetime.time(9, 0, 24, 400202), help_text='Heure préférée pour recevoir les rappels de lecture', verbose_name='Heure des rappels')),
                ('timezone', models.CharField(default='Europe/Paris', max_length=50, verbose_name='Fuseau horaire')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Préférences de notification',
                'verbose_name_plural': 'Préférences de notification',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('body', models.TextField(verbose_name='Corps du message')),
                ('notification_type', models.CharField(choices=[('reading_reminder', 'Rappel de lecture'), ('verse_of_day', 'Verset du jour'), ('couple_notification', 'Notification de couple'), ('reading_plan_update', 'Mise à jour plan de lecture'), ('achievement_unlocked', 'Réussite débloquée'), ('general', 'Générale')], max_length=50, verbose_name='Type')),
                ('recipient_type', models.CharField(choices=[('user', 'Utilisateur'), ('topic', 'Topic'), ('bulk', 'Groupe')], max_length=20, verbose_name='Type de destinataire')),
                ('topic_name', models.CharField(blank=True, max_length=100, verbose_name='Nom du topic')),
                ('custom_data', models.JSONField(blank=True, default=dict, verbose_name='Données personnalisées')),
                ('status', models.CharField(choices=[('sent', 'Envoyée'), ('failed', 'Échec'), ('pending', 'En attente')], default='pending', max_length=20, verbose_name='Statut')),
                ('firebase_message_id', models.CharField(blank=True, max_length=255, verbose_name='ID message Firebase')),
                ('error_message', models.TextField(blank=True, verbose_name="Message d'erreur")),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='Envoyé le')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Destinataire')),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_notifications', to=settings.AUTH_USER_MODEL, verbose_name='Envoyé par')),
            ],
            options={
                'verbose_name': 'Historique de notification',
                'verbose_name_plural': 'Historique des notifications',
                'db_table': 'notification_history',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.TextField(verbose_name='Token FCM')),
                ('device_type', models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], default='android', max_length=20, verbose_name="Type d'appareil")),
                ('is_active', models.BooleanField(default=True, verbose_name='Actif')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Mis à jour le')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fcm_token_info', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token FCM',
                'verbose_name_plural': 'Tokens FCM',
                'db_table': 'fcm_tokens',
            },
        ),
    ]
