#!/bin/bash

set -o errexit
set -o nounset

worker_ready() {
    celery -A notification inspect ping
}

until worker_ready; do
   >&2 echo "Celery workers are not available :-("
   sleep 1
done
>&2 echo "Celery workers are available and ready!....:-)"

celery -A notification --broker="${CELERY_BROKER_URL}" flower
