"""
Django settings for notification project.

Generated by 'django-admin startproject' using Django 4.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""

from pathlib import Path

import os
from dotenv import load_dotenv
import environ

env = environ.Env()
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DJANGO_DEBUG", False)

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    # 'drf_yasg',
    'mailing', 
    'exigence',
    # Healthchecks
    'health_check',  # required
    'health_check.db',  
    'health_check.contrib.migrations',   
    'rest_framework',

    'django_celery_results',
    'django_celery_beat',
    'drf_spectacular'
]


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware', 
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Configuration de REST Framework
REST_FRAMEWORK = {
    # Utilisez DRF Spectacular pour la génération de schéma
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    
    # Autres configurations REST Framework
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}
# Autoriser tous les CORS - À utiliser uniquement en développement
CORS_ALLOW_ALL_ORIGINS = True
 
SPECTACULAR_SETTINGS = {
    'TITLE': 'API d\'exigence',
    'DESCRIPTION': 'API pour créer des exigences et envoyer des notifications',
    'VERSION': '1.0.0',
    
    # Autres options utiles
    'SERVE_INCLUDE_SCHEMA': False,  # Ne pas inclure le schema dans la liste des endpoints
    
    # Configuration d'authentification pour Swagger UI
    'SECURITY': [
        {
            'Token': [],
        }
    ],
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': False,
    },
    
    # Personnalisation avancée (optionnel)
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    
    # Filtres pour exclure certains endpoints (optionnel)
    # 'EXCLUDE_PATHS': ['/api/admin/'],
}

ROOT_URLCONF = 'notification.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'notification.wsgi.application'
 
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases

DATABASES = {
    'default': {
        # Add 'postgresql_psycopg2', 'mysql', 'sqlite3' or 'oracle'.
        'ENGINE': os.getenv("ENGINE", "django.db.backends.sqlite3"),
        # Or path to database file if using sqlite3.
        'NAME': os.getenv("POSTGRES_DB", BASE_DIR / "db.sqlite3"),
        'USER': os.getenv("POSTGRES_USER", "user"),
        'PASSWORD': os.getenv("POSTGRES_PASSWORD", "password"),
        # 'HOST':'db',
        # Empty for localhost through domain sockets or '127.0.0.1' for localhost through TCP.
        'HOST': os.getenv("POSTGRES_HOST", "localhost"),
        # Set to empty string for default.
        'PORT':  os.getenv("POSTGRES_PORT", "5432"),
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]
  
# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Celery configuration
CELERY_TIMEZONE = os.environ.get("CELERY_TIMEZONE", "Africa/Douala")
CELERY_TASK_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_CACHE_BACKEND = 'django-cache'
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_RESULT_EXPIRES = 18000
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
CELERY_IMPORTS = ["mailing.utils"]
CELERY_BROKER_URL = os.environ.get("CELERY_BROKER_URL", "redis://redis:6379/0")
CELERY_RESULT_BACKEND = os.environ.get("CELERY_RESULT_BACKEND", "redis://redis:6379/0")
REDIS_URL = os.environ.get("REDIS_URL", "redis://redis:6379/0")


# Healthchecks: https://github.com/revsys/django-health-check
HEALTH_CHECK = {

    "SUBSETS": {
        "startup-probe": ["MigrationsHealthCheck", "DatabaseBackend"],
        "liveness-probe": ["DatabaseBackend"],
        # "liveness-probe": ["DatabaseBackend", "CeleryHealthCheckCelery", "CeleryPingHealthCheck"],
    },
}

load_dotenv()

# SECURITY WARNING: keep the secret key used in production secret!
 

SECRET_KEY = env(
    "DJANGO_SECRET_KEY",
    default="django-insecure-o(%d_rzzf^g01b1bm9j--$wv**&fvez9y_!bmkl(xupof2qzfj",
)

ALLOWED_HOSTS = ["*"]


EMAIL_HOST = os.getenv(
    "EMAIL_HOST", 'smtp.gmail.com')
EMAIL_PORT = os.getenv(
    "EMAIL_PORT", 587)
EMAIL_USE_TLS = True
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER", 'avotreecoute@klivar.com>')
EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD", '!Klivardev1')
APP_NAME = 'Klivar'



 