# Generated by Django 4.2.7 on 2025-03-13 06:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExigenceMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', models.CharField(max_length=255, verbose_name="Objet de l'exigence")),
                ('description', models.TextField(verbose_name="Description détaillée de l'exigence")),
                ('company', models.CharField(max_length=255, verbose_name="Nom de l'entreprise")),
                ('dest_email', models.EmailField(max_length=254, verbose_name='Email du destinataire')),
                ('sender_name', models.CharField(max_length=255, verbose_name="Nom de l'expéditeur")),
                ('dest_name', models.CharField(max_length=255, verbose_name='Nom du destinataire')),
                ('url', models.URLField(verbose_name="URL pour le lien front end de l'exigence")),
                ('method', models.CharField(max_length=100, verbose_name="Méthode de l'exigence")),
                ('base_url', models.URLField(verbose_name="URL pour les images de référence de l'exigence")),
                ('jwt_token', models.TextField(verbose_name='Token user config exigence')),
                ('scope', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name="Liste des périmètres d'application de l'exigence")),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date de création')),
                ('is_send', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Exigence',
                'verbose_name_plural': 'Exigences',
                'ordering': ['-created_at'],
            },
        ),
    ]
