# Generated by Django 4.2.7 on 2025-03-14 00:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='auth_code',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=255, null=True)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('expires_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
