# Generated by Django 4.2.7 on 2025-03-14 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0002_auth_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exigencemail',
            name='company',
            field=models.TextField(verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='method',
            field=models.TextField(verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='object',
            field=models.TextField(verbose_name="Description détaillée de l'exigence"),
        ),
    ]
