# Generated by Django 4.2.7 on 2025-03-14 01:43

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0003_alter_exigencemail_company_alter_exigencemail_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exigencemail',
            name='scope',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, null=True, size=None, verbose_name="Liste des périmètres d'application de l'exigence"),
        ),
    ]
