# Generated by Django 4.2.7 on 2025-03-14 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0004_alter_exigencemail_scope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exigencemail',
            name='base_url',
            field=models.TextField(verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='url',
            field=models.TextField(verbose_name="Description détaillée de l'exigence"),
        ),
    ]
