# Generated by Django 4.2.7 on 2025-03-14 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0005_alter_exigencemail_base_url_alter_exigencemail_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='id_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
