# Generated by Django 4.2.7 on 2025-03-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0006_exigencemail_id_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='id_analysis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
