# Generated by Django 4.2.7 on 2025-03-20 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0007_exigencemail_id_analysis'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='id_indicateur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exigencemail',
            name='id_reporting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
