# Generated by Django 4.2.7 on 2025-04-03 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0008_exigencemail_id_indicateur_exigencemail_id_reporting'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='dealine',
            field=models.CharField(max_length=255, null=True, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AddField(
            model_name='exigencemail',
            name='time',
            field=models.CharField(max_length=255, null=True, verbose_name="Nom de l'expéditeur"),
        ),
    ]
