# Generated by Django 4.2.7 on 2025-04-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0009_exigencemail_dealine_exigencemail_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='start_date',
            field=models.CharField(max_length=255, null=True, verbose_name='Date de début'),
        ),
    ]
