# Generated by Django 4.2.7 on 2025-04-15 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0010_exigencemail_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='type_task',
            field=models.CharField(max_length=255, null=True, verbose_name='Date de début'),
        ),
    ]
