# Generated by Django 4.2.7 on 2025-04-15 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0011_exigencemail_type_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exigencemail',
            name='base_url',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='company',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='dest_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email du destinataire'),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='dest_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom du destinataire'),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='jwt_token',
            field=models.TextField(blank=True, null=True, verbose_name='Token user config exigence'),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='method',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='object',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name="Nom de l'expéditeur"),
        ),
        migrations.AlterField(
            model_name='exigencemail',
            name='url',
            field=models.TextField(blank=True, null=True, verbose_name="Description détaillée de l'exigence"),
        ),
    ]
