# Generated by Django 4.2.7 on 2025-04-27 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0012_alter_exigencemail_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='id_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
