# Generated by Django 4.2.7 on 2025-04-27 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0013_exigencemail_id_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='is_answer',
            field=models.BooleanField(default=False),
        ),
    ]
