# Generated by Django 4.2.7 on 2025-04-28 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0014_exigencemail_is_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='lang',
            field=models.CharField(default='fr-FR', max_length=255),
        ),
    ]
