# Generated by Django 4.2.7 on 2025-04-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0015_exigencemail_lang'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='is_notification',
            field=models.BooleanField(default=False),
        ),
    ]
