# Generated by Django 4.2.7 on 2025-05-15 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0016_exigencemail_is_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='is_approver',
            field=models.BooleanField(default=False),
        ),
    ]
