# Generated by Django 4.2.7 on 2025-06-13 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0017_exigencemail_is_approver'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='exigencemail',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exigencemail',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
