# Generated by Django 4.2.7 on 2025-11-03 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0018_exigencemail_sent_exigencemail_sent_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit', models.CharField(blank=True, max_length=255, null=True)),
                ('value', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_ups', to='exigence.exigencemail')),
            ],
        ),
        migrations.CreateModel(
            name='ActorFollow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.TextField(blank=True, null=True)),
                ('id_user', models.CharField(blank=True, max_length=255, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('follow_up', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actor_follow_up', to='exigence.followup')),
            ],
        ),
    ]
