# Generated by Django 4.2.7 on 2025-11-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0019_followup_actorfollow'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='id_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followup',
            name='id_project',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
