# Generated by Django 4.2.7 on 2025-11-05 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0020_exigencemail_id_project_followup_id_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='task',
        ),
        migrations.AddField(
            model_name='followup',
            name='id_action',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
