# Generated by Django 4.2.7 on 2025-11-05 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0021_remove_followup_task_followup_id_action'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='id_client',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='actorfollow',
            name='id_user',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='id_action',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='followup',
            name='id_project',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
