# Generated by Django 4.2.7 on 2025-11-05 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0022_followup_id_client_alter_actorfollow_id_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
