# Generated by Django 4.2.7 on 2025-11-06 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0023_followup_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='actorfollow',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='exigencemail',
            name='id_client',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
