# Generated by Django 4.2.7 on 2025-11-06 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0024_actorfollow_task_id_exigencemail_id_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='followup',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
