# Generated by Django 4.2.7 on 2025-11-06 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0025_followup_jwt_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='exigencemail',
            name='role',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
