# Generated by Django 4.2.7 on 2025-11-07 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exigence', '0026_exigencemail_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followup',
            name='jwt_token',
        ),
        migrations.AddField(
            model_name='actorfollow',
            name='jwt_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
