---
# Global vars
traefik_network: traefik-public

# DB settings
tmp_back_db_host: "{{ vault_db_host }}"
tmp_back_db_name: "{{ vault_db_name }}"
tmp_back_db_user: "{{ vault_db_user }}"
tmp_back_db_password: "{{ vault_db_password }}"
tmp_back_db_port: "{{ vault_db_port }}"

# Django settings
tmp_back_django_secret_key: "{{ vault_django_secret_key }}"

firebase_type": "{{ firebase_type }}"  
firebase_project_id : "{{ firebase_project_id }}" 
firebase_private_key_id": "{{ firebase_private_key_id }}"
firebase_private_key": "{{ firebase_private_key }}"

firebase_client_email": "{{ firebase_client_email }}"

firebase_client_id": "{{ firebase_client_id }}"
firebase_auth_uri": "{{ firebase_auth_uri }}"
firebase_token_uri": "{{ firebase_token_uri }}"
firebase_auth_provider_x509_cert_url": "{{ firebase_auth_provider_x509_cert_url }}"  
firebase_client_x509_cert_url: "{{ firebase_client_x509_cert_url }}"  
firebase_universe_domain": "{{ firebase_universe_domain }}"
