---
# Global vars
traefik_network: traefik-public

# DB settings
klivar_backend_db_host: "{{ vault_db_host }}"
klivar_backend_db_name: "{{ vault_db_name }}"
klivar_backend_db_user: "{{ vault_db_user }}"
klivar_backend_db_password: "{{ vault_db_password }}"
klivar_backend_db_port: "{{ vault_db_port }}"

# Django settings
klivar_backend_django_secret_key: "{{ vault_django_secret_key }}"
