# Generated by Django 4.2.7 on 2025-10-17 09:09

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_instance', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('actors', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('perimeter', django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), size=None)),
                ('type', models.CharField(max_length=255)),
                ('format', models.CharField(max_length=255)),
                ('link', models.CharField(max_length=255)),
                ('recurrence_config', models.JSONField()),
                ('ponctuel_config', models.JSONField()),
                ('client', models.JSONField()),
                ('lang', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Instance Board',
                'verbose_name_plural': 'Instance Boards',
                'db_table': 'instance_board',
            },
        ),
    ]
