# Generated by Django 4.2.7 on 2025-10-17 10:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceboard',
            name='url_connect',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='actors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='client',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='format',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='id_instance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='lang',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='link',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='perimeter',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, null=True, size=None),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='ponctuel_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='recurrence_config',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='instanceboard',
            name='type',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
