# Generated by Django 4.2.7 on 2025-10-17 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0002_instanceboard_url_connect_alter_instanceboard_actors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='instanceboard',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
