# Generated by Django 4.2.7 on 2025-10-17 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_instanceboard_reference'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommitteeBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_task', models.CharField(blank=True, max_length=255, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('instance_board', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='board.instanceboard')),
            ],
            options={
                'db_table': 'committee_board',
            },
        ),
    ]
