# Generated by Django 4.2.7 on 2025-10-20 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_committeeboard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='committeeboard',
            name='date',
        ),
    ]
