# Generated by Django 4.2.7 on 2025-10-20 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_remove_committeeboard_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='committeeboard',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
